### PR TITLE
Merge development to master

### PR DESCRIPTION
**Pull request by Karuhanga**

### CODE REVIEW

**Comment by Karuhanga** [comment]
> @Karuhanga why aren't you committing to the master branch?

All done.

**Comment by dkayiwa** [comment]
@Karuhanga apart from copying classes and a few things from the old code base to this one, can you give a summary of how this new codebase is different from the old one?

**Comment by Karuhanga** [comment]
> @Karuhanga apart from copying classes and a few things from the old code base to this one, can you give a summary of how this new codebase is different from the old one?

#### Create and Edit dictionaries page
- Better error handling
- Explicit reference to the source
- Eliminated duplication- single form for create and edit

#### View concepts page, Add concepts to collection
- Eliminated duplication(for example, we had multiple pages for the page all handling the same fetch and display concepts logic, filtering components, duplicate actions)
- Consistent ways of doing this across the application, for example loading, error handling, long running actions
- Better UI, more consistent loading
- Proper and explicit permissions

#### Create and edit, view concept page
- Eliminated duplication(we had components with similar logic for creating and editing concepts. That's now a single one, multiple components for mapping types with similar, yet disparate logic, same goes for the names and descriptions table)
- better UI, more responsive loading
- We do not load all sources/ all concepts at once anymore
- Better checks and logic for when to update concept references in a dictionary
- Proper and explicit permissions

#### Overall
- Better error handling, better handling of edge cases
- Cleaner, smaller code base
- Type safety
- Better edge case call outs and comments

Interesting that you say copying classes :). I hardly copy pasted anything. A lot of learning and understanding why certain parts weren't working properly, no copy pasting :).

**Comment by Karuhanga** [comment]
@dkayiwa any more feedback on this?

**Comment by dkayiwa** [comment]
@Karuhanga have you committed any tests that i can look at?

**Pull request merged**
